"""initial schema

Revision ID: 2c1d8d82eac8
Revises: 
Create Date: 2026-09-17 20:18:03.704824
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2c1d8d82eac8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('STARTUP', 'LEGACY', 'SME', 'GOVERNMENT', name='company_type'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('profile_text', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dpiit_recognised', sa.Boolean(), nullable=False),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('founder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('identity_ref', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identity_ref')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('GOVERNMENT', 'STARTUP', 'EXPERT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('company_founder',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['founder_id'], ['founder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'founder_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='level'), nullable=True),
    sa.Column('innovation_potential', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='level'), nullable=True),
    sa.Column('tier', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='tier'), nullable=True),
    sa.Column('tier_explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ANALYZED', 'APPROVED', 'PUBLISHED', 'EVALUATION', 'PILOT', 'COMPLETED', 'CANCELLED', name='challenge_status'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('requires_onsite', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structured_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kpis_locked', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=80), nullable=False),
    sa.Column('rule_type', sa.Enum('AMOUNT', 'PERCENTAGE', 'COUNT', 'DAYS', 'SCORE', name='rule_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_rule_rule_name'), 'procurement_rule', ['rule_name'], unique=False)
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('awarded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('measurement_method', sa.Text(), nullable=True),
    sa.Column('claimed_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('claimed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', name='kpi_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partnership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('legacy_partner_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('startup_scope', sa.Text(), nullable=True),
    sa.Column('execution_scope', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'ACTIVE', 'COMPLETED', 'TERMINATED', name='partnership_status'), nullable=False),
    sa.Column('milestone_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legacy_partner_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'EVIDENCE_SUBMITTED', 'VALIDATED', 'CLOSED', name='pilot_status'), nullable=False),
    sa.Column('recommended_outcome', sa.Enum('SCALE', 'MODIFY', 'REJECT', name='pilot_outcome'), nullable=True),
    sa.Column('recommendation_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.Enum('SCALE', 'MODIFY', 'REJECT', name='pilot_outcome'), nullable=True),
    sa.Column('outcome_decided_by', sa.Integer(), nullable=True),
    sa.Column('outcome_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_note', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('planned_end_on', sa.Date(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_decided_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'DECLINED', 'AWARDED', 'WITHDRAWN', name='proposal_status'), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decline_reason_code', sa.Enum('FAILED_GENERAL_ELIGIBILITY', 'FAILED_STARTUP_LANE_ELIGIBILITY', 'BELOW_TECHNICAL_SCORE_THRESHOLD', 'CAPABILITY_MISMATCH', 'KPI_TARGETS_NOT_ADDRESSED', 'DEPLOYMENT_READINESS_INSUFFICIENT', 'SECURITY_COMPLIANCE_GAP', 'INCOMPLETE_SUBMISSION', 'ROTATION_RULE_APPLIED', 'STRONGER_ALTERNATIVE_SELECTED', 'TIER_ACCESS_RESTRICTION', name='decline_reason_code'), nullable=True),
    sa.Column('decline_detail', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'startup_id', name='uq_proposal_once')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    op.drop_table('pilot')
    op.drop_table('partnership')
    op.drop_table('kpi')
    op.drop_table('award')
    op.drop_index(op.f('ix_procurement_rule_rule_name'), table_name='procurement_rule')
    op.drop_table('procurement_rule')
    op.drop_table('challenge')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('company_founder')
    op.drop_table('app_user')
    op.drop_table('founder')
    op.drop_table('department')
    op.drop_table('company')
    # ### end Alembic commands ###
