import { AlertTriangle, CheckCircle2, Cpu, Trophy, UserSearch } from "lucide-react"
import { ScoreGauge } from "@/components/score-gauge"
import { ComponentScoreBar } from "@/components/component-score-bar"
import { cn } from "@/lib/utils"

export interface NormalizedMatch {
  startupId: string
  companyName: string
  rank: number
  overallScore: number
  semanticSimilarity: number
  technologyMatch: number
  domainMatch: number
  experienceScore: number
  readinessScore: number
  reasons: string[]
  gaps: string[]
}

/**
 * One ranked startup, with the reasoning behind its position.
 *
 * The card is built to answer "why is this one first?" rather than to display
 * a number. The overall score sits beside the five weighted components that
 * produced it, and the reasons and gaps — both generated by the backend from
 * the same component scores — sit alongside so the ranking is inspectable
 * rather than asserted.
 *
 * The weights shown against each bar mirror the documented formula and match
 * `ai_matching_config` in the database. Every value here comes from the
 * matching API; nothing is computed or padded client-side.
 */

/** A plain-language band for the overall score. Purely presentational. */
function strengthLabel(score: number): { label: string; tone: string } {
  if (score >= 70) return { label: "Strong match", tone: "text-success-700 bg-success-50 border-success-100" }
  if (score >= 50) return { label: "Moderate match", tone: "text-brand-700 bg-brand-50 border-brand-100" }
  if (score >= 30) return { label: "Partial match", tone: "text-warning-700 bg-warning-50 border-warning-100" }
  return { label: "Weak match", tone: "text-slate-600 bg-slate-50 border-slate-200" }
}

export function MatchCandidateCard({
  match,
  onViewProfile,
  actions,
}: {
  match: NormalizedMatch
  onViewProfile: (startupId: string) => void
  actions?: React.ReactNode
}) {
  const top = match.rank === 1
  const strength = strengthLabel(match.overallScore)

  return (
    <article
      className={cn(
        "rounded-lg border bg-white transition-colors",
        top ? "border-brand-300 ring-1 ring-brand-100" : "border-slate-200",
      )}
      aria-label={`Rank ${match.rank}: ${match.companyName}`}
    >
      {top && (
        <div className="flex items-center gap-1.5 rounded-t-lg border-b border-brand-100 bg-brand-50 px-4 py-1.5">
          <Trophy className="h-3.5 w-3.5 text-brand-700" aria-hidden />
          <span className="text-[11px] font-semibold uppercase tracking-wide text-brand-800">
            Highest ranked candidate
          </span>
        </div>
      )}

      <div className="grid gap-5 p-5 lg:grid-cols-[auto_minmax(0,1fr)_minmax(0,1fr)]">
        {/* Score */}
        <div className="flex flex-row items-center gap-4 lg:flex-col lg:justify-start lg:gap-2">
          <div className="flex flex-col items-center">
            <span className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
              Rank #{match.rank}
            </span>
            <ScoreGauge score={match.overallScore} size={104} />
          </div>
          <span
            className={cn(
              "rounded-md border px-2 py-0.5 text-[11px] font-medium",
              strength.tone,
            )}
          >
            {strength.label}
          </span>
        </div>

        {/* Identity + component breakdown */}
        <div className="min-w-0 space-y-3">
          <div>
            <h4 className="text-base font-semibold text-slate-900">{match.companyName}</h4>
            <button
              onClick={() => onViewProfile(match.startupId)}
              className="mt-0.5 flex items-center gap-1 rounded text-xs font-medium text-brand-700 hover:underline"
            >
              <UserSearch className="h-3.5 w-3.5" aria-hidden /> View full profile
            </button>
          </div>

          <div>
            <p className="mb-1.5 text-[11px] font-medium uppercase tracking-wide text-slate-500">
              Score components
            </p>
            <div className="space-y-2">
              <ComponentScoreBar label="Semantic fit" value={match.semanticSimilarity} weight={0.35} />
              <ComponentScoreBar label="Technology fit" value={match.technologyMatch} weight={0.2} />
              <ComponentScoreBar label="Domain fit" value={match.domainMatch} weight={0.15} />
              <ComponentScoreBar label="Experience" value={match.experienceScore} weight={0.15} />
              <ComponentScoreBar label="Pilot readiness" value={match.readinessScore} weight={0.15} />
            </div>
          </div>
        </div>

        {/* Reasoning */}
        <div className="min-w-0 space-y-3">
          {match.reasons.length > 0 && (
            <div>
              <p className="mb-1.5 flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-success-700">
                <CheckCircle2 className="h-3.5 w-3.5" aria-hidden /> Why this startup matches
              </p>
              <ul className="space-y-1.5">
                {match.reasons.map((reason, index) => (
                  <li key={index} className="flex gap-2 text-sm leading-snug text-slate-700">
                    <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-success-500" aria-hidden />
                    {reason}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {match.gaps.length > 0 && (
            <div>
              <p className="mb-1.5 flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-warning-700">
                <AlertTriangle className="h-3.5 w-3.5" aria-hidden /> Potential gaps
              </p>
              <ul className="space-y-1.5">
                {match.gaps.map((gap, index) => (
                  <li key={index} className="flex gap-2 text-sm leading-snug text-slate-700">
                    <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-warning-500" aria-hidden />
                    {gap}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {actions && <div className="flex flex-wrap gap-2 pt-1">{actions}</div>}
        </div>
      </div>
    </article>
  )
}

/**
 * Header for a completed matching run.
 *
 * Surfaces how many candidates were actually considered and which provider
 * produced the scores — both returned by the API and previously discarded.
 * Stating the analysed count matters: it shows the ranking is a shortlist out
 * of a real field, not an arbitrary handful.
 */
export function MatchingSummary({
  analysed,
  shown,
  provider,
}: {
  analysed: number | null
  shown: number
  provider: string | null
}) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-accent-100 bg-accent-50/60 px-4 py-3">
      <div className="flex items-start gap-2.5">
        <Cpu className="mt-0.5 h-4 w-4 shrink-0 text-accent-600" aria-hidden />
        <div>
          <p className="text-sm font-medium text-slate-900">
            {analysed !== null
              ? `${analysed} eligible startups analysed`
              : `${shown} ranked candidates`}
            {analysed !== null && shown < analysed && ` · top ${shown} shown`}
          </p>
          <p className="text-xs text-slate-600">
            Ranked on a weighted formula across five components. Scores and explanations
            are generated by the platform and are advisory.
          </p>
        </div>
      </div>
      {provider && (
        <span className="rounded border border-accent-100 bg-white px-2 py-0.5 text-[11px] text-accent-700">
          {provider === "local-fallback" ? "Local model" : provider}
        </span>
      )}
    </div>
  )
}
