package com.innovategov.backend.entity.enums;

public enum NotificationType {
    MATCH_READY, PROPOSAL_SUBMITTED, PROPOSAL_STATUS_CHANGE, DOCUMENT_VERIFIED,
    DOCUMENT_FLAGGED, EVALUATION_ASSIGNED, EVALUATION_SUBMITTED, SHORTLISTED,
    PILOT_CREATED, MILESTONE_DUE, MILESTONE_UPDATED, RECOMMENDATION_READY, GENERAL
}
