"""Barrier analysis.

When an officer drafts a challenge, they usually paste in the eligibility
criteria their department has always used.  This engine flags the ones that
exclude startups, says whether the criterion is essential to this procurement or
simply traditional, and cites what the platform uses instead.

It flags.  The officer decides: nothing here blocks a challenge, and nothing
here is generated by an LLM.

The catalogue holds exactly the three barrier types the specification names.
Anything else is returned as unclassified for the officer to judge.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass

from app.services.rules import RulesService

MIN_TECH_SCORE = "MIN_TECH_SCORE"


class BarrierCode(str, enum.Enum):
    """Barrier types the engine recognises. Not persisted, so not a database enum."""

    TURNOVER_FLOOR = "TURNOVER_FLOOR"
    YEARS_IN_BUSINESS = "YEARS_IN_BUSINESS"
    PRIOR_GOVERNMENT_PROJECTS = "PRIOR_GOVERNMENT_PROJECTS"
    OTHER = "OTHER"


class Classification(str, enum.Enum):
    ESSENTIAL = "ESSENTIAL"
    TRADITIONAL = "TRADITIONAL"
    UNCLASSIFIED = "UNCLASSIFIED"


@dataclass(frozen=True)
class BarrierType:
    label: str
    excludes_startups: bool
    classification: Classification
    why: str
    # Which rule the platform reads instead of this criterion, if any.
    replaced_by_rule: str | None


CATALOGUE: dict[BarrierCode, BarrierType] = {
    BarrierCode.TURNOVER_FLOOR: BarrierType(
        label="Minimum annual turnover",
        excludes_startups=True,
        classification=Classification.TRADITIONAL,
        why=(
            "A turnover floor is a proxy for delivery capacity. A company incorporated two "
            "years ago cannot meet it however capable it is, so the criterion screens on age "
            "rather than on capability."
        ),
        replaced_by_rule=MIN_TECH_SCORE,
    ),
    BarrierCode.YEARS_IN_BUSINESS: BarrierType(
        label="Minimum years in business",
        excludes_startups=True,
        classification=Classification.TRADITIONAL,
        why=(
            "A years-in-business floor screens on how long a company has existed rather "
            "than on what it can deliver, which is the one thing a young company can "
            "never acquire in time to bid."
        ),
        replaced_by_rule=MIN_TECH_SCORE,
    ),
    BarrierCode.PRIOR_GOVERNMENT_PROJECTS: BarrierType(
        label="Prior government project experience",
        excludes_startups=True,
        classification=Classification.TRADITIONAL,
        why=(
            "Requiring prior government work is circular for a first-time supplier: it can "
            "only be satisfied by companies that have already been selected before."
        ),
        replaced_by_rule=MIN_TECH_SCORE,
    ),
}

# What the platform offers in place of the traditional proofs above.
PILOT_SUBSTITUTE = (
    "A KPI-tracked pilot, with targets validated by someone other than the supplier, is the "
    "evidence of reliability this platform uses in place of turnover and prior-experience proof."
)


@dataclass(frozen=True)
class ProposedCriterion:
    code: BarrierCode
    detail: str


@dataclass(frozen=True)
class CriterionFlag:
    code: BarrierCode
    label: str
    detail: str
    excludes_startups: bool | None
    classification: Classification
    reason: str
    rule_cited: str | None
    officer_action: str

    def as_dict(self) -> dict:
        return {
            "code": self.code.value,
            "label": self.label,
            "detail": self.detail,
            "excludes_startups": self.excludes_startups,
            "classification": self.classification.value,
            "reason": self.reason,
            "rule_cited": self.rule_cited,
            "officer_action": self.officer_action,
        }


@dataclass(frozen=True)
class BarrierAnalysis:
    criteria: list[CriterionFlag]
    flagged: int
    summary: str

    def as_dict(self) -> dict:
        return {
            "criteria": [flag.as_dict() for flag in self.criteria],
            "flagged": self.flagged,
            "summary": self.summary,
        }


def analyse(rules: RulesService, criteria: list[ProposedCriterion]) -> BarrierAnalysis:
    """Flag proposed eligibility criteria that shut startups out."""

    flags: list[CriterionFlag] = []

    for proposed in criteria:
        barrier = CATALOGUE.get(proposed.code)

        if barrier is None:
            flags.append(
                CriterionFlag(
                    code=proposed.code,
                    label="Unrecognised criterion",
                    detail=proposed.detail,
                    excludes_startups=None,
                    classification=Classification.UNCLASSIFIED,
                    reason=(
                        "The engine has no entry for this criterion, so it makes no claim "
                        "about it. Judge whether it is essential to this procurement."
                    ),
                    rule_cited=None,
                    officer_action="Officer decides whether to keep this criterion.",
                )
            )
            continue

        rule_citation = None
        if barrier.replaced_by_rule:
            rule_citation = rules.get(barrier.replaced_by_rule).cite()

        reason = barrier.why
        if rule_citation:
            reason = f"{reason} {PILOT_SUBSTITUTE} The platform applies {rule_citation} instead."

        flags.append(
            CriterionFlag(
                code=proposed.code,
                label=barrier.label,
                detail=proposed.detail,
                excludes_startups=barrier.excludes_startups,
                classification=barrier.classification,
                reason=reason,
                rule_cited=rule_citation,
                officer_action=(
                    "Officer decides: keep this criterion, or drop it and rely on the "
                    "KPI-tracked pilot."
                ),
            )
        )

    flagged = sum(flag.excludes_startups is True for flag in flags)
    summary = (
        f"{flagged} of {len(flags)} proposed criteria exclude startups. "
        f"Nothing has been changed: these are flags for the officer, not a block."
    )
    return BarrierAnalysis(criteria=flags, flagged=flagged, summary=summary)
